import SEO from './SEO'

export default function TermsAndConditions() {
    return (
        <main style={{ padding: 'var(--space-10) 0', minHeight: '100vh' }}>
            <SEO
                title="Terms and Conditions | Goschedule.ai"
                description="Terms and conditions for using Goschedule.ai products and services."
                canonical="https://www.goschedule.ai/terms-and-conditions"
            />
            <div className="container" style={{ maxWidth: '800px' }}>

                {/* Header */}
                <div style={{ marginBottom: 'var(--space-8)' }}>
                    <div className="badge" style={{ marginBottom: 'var(--space-3)' }}>Legal</div>
                    <h1 className="h2" style={{ marginBottom: 'var(--space-2)' }}>Terms and Conditions</h1>
                    <p className="body-sm">Last updated: April 3, 2026</p>
                </div>

                {/* Content */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-5)' }}>

                    <Section title="1. Introduction">
                        <p>
                            Welcome to Goschedule.ai ("Company," "we," "our," or "us"). These Terms and Conditions ("Terms") govern your access to and use of the Goschedule.ai website, platform, tools, and services (collectively, the "Services"). By accessing our website or engaging our Services, you ("Client," "you," or "your") agree to be bound by these Terms.
                        </p>
                        <p>
                            If you do not agree to these Terms, please do not use our Services. We reserve the right to modify these Terms at any time. Continued use of the Services after any changes constitutes your acceptance of the revised Terms.
                        </p>
                    </Section>

                    <Section title="2. Definitions">
                        <ul>
                            <li><strong>"Services"</strong> refers to all offerings provided by Goschedule.ai, including but not limited to AI-powered lead generation, outbound automation systems, consulting, and related support.</li>
                            <li><strong>"Client"</strong> refers to any individual, business, or entity that engages Goschedule.ai for its Services.</li>
                            <li><strong>"Sales-Qualified Lead" (SQL)</strong> means a prospective business contact that has been identified, verified, and qualified through our AI systems as meeting predefined criteria agreed upon with the Client.</li>
                            <li><strong>"Platform"</strong> refers to the proprietary tools, dashboards, and technology infrastructure operated by Goschedule.ai.</li>
                            <li><strong>"Content"</strong> means any text, data, graphics, or other materials provided through or generated by the Services.</li>
                        </ul>
                    </Section>

                    <Section title="3. Services Offered">
                        <p>Goschedule.ai provides the following core Services to B2B companies:</p>
                        <ul>
                            <li><strong>AI-Powered Lead Generation:</strong> Automated identification and qualification of sales-qualified leads using proprietary AI systems, without the requirement for paid advertising.</li>
                            <li><strong>Outbound Automation Setup:</strong> Configuration and deployment of multi-channel outreach systems, including email sequences, LinkedIn automation, and other digital outreach infrastructure.</li>
                            <li><strong>AI Consulting &amp; Strategy:</strong> Strategic consulting on leveraging AI tools for sales pipeline development, workflow optimization, and growth infrastructure design.</li>
                            <li><strong>Performance Monitoring:</strong> Analytics dashboards and reporting to track engagement, pipeline progression, and qualified conversation metrics.</li>
                        </ul>
                        <p>
                            Specific deliverables and scope shall be outlined in a separate Service Agreement or Statement of Work ("SOW") executed between Goschedule.ai and the Client.
                        </p>
                    </Section>

                    <Section title="4. User Responsibilities">
                        <p>By using our Services, you agree to:</p>
                        <ul>
                            <li>Provide accurate and up-to-date business information, including Ideal Customer Profile (ICP) details, target market specifications, and any other data reasonably required for service delivery.</li>
                            <li>Use the Services solely for lawful business purposes and in compliance with all applicable local, national, and international laws and regulations.</li>
                            <li>Refrain from misusing, reverse-engineering, or attempting to compromise the integrity of our platform, technology, or systems.</li>
                            <li>Maintain the confidentiality of any credentials, API keys, or access tokens provided by Goschedule.ai.</li>
                            <li>Cooperate in good faith with Goschedule.ai for onboarding, feedback sessions, and any adjustments to the service scope.</li>
                            <li>Not resell, sublicense, or redistribute the Services or any output generated therefrom without prior written consent.</li>
                        </ul>
                    </Section>

                    <Section title="5. Payment Terms">
                        <ul>
                            <li><strong>Pricing:</strong> Fees for Services shall be as specified in the applicable SOW or pricing plan agreed upon prior to engagement.</li>
                            <li><strong>Performance-Based Model:</strong> Where a performance-based pricing model is agreed, payment obligations arise only upon the delivery of qualified leads as defined in the SOW. If no qualified leads are delivered within the agreed engagement period, no payment shall be due from the Client.</li>
                            <li><strong>Invoicing:</strong> Invoices shall be issued monthly or as specified in the SOW. Payment is due within fifteen (15) business days of invoice date unless otherwise agreed.</li>
                            <li><strong>Late Payments:</strong> Overdue payments may accrue interest at 1.5% per month or the maximum rate permitted by applicable law, whichever is lower.</li>
                            <li><strong>Taxes:</strong> All fees are exclusive of applicable taxes, including GST. The Client is responsible for all applicable taxes unless expressly stated otherwise.</li>
                            <li><strong>Refunds:</strong> Refund policies shall be governed by the terms of the applicable SOW. Prepaid retainer fees are non-refundable unless otherwise specified.</li>
                        </ul>
                    </Section>

                    <Section title="6. Limitation of Liability">
                        <ul>
                            <li>Goschedule.ai shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, revenue, data, or business opportunities, arising from the use of or inability to use our Services.</li>
                            <li>Our total aggregate liability under these Terms shall not exceed the total fees paid by the Client to Goschedule.ai in the twelve (12) months preceding the claim.</li>
                            <li>Goschedule.ai does not guarantee specific business outcomes, conversion rates, or revenue results. Lead qualification is based on predefined criteria and AI analysis, which may not guarantee final sales conversion.</li>
                            <li>We are not responsible for third-party tool failures, email deliverability issues caused by the Client's domain reputation, or data inaccuracies in external databases used for lead sourcing.</li>
                        </ul>
                    </Section>

                    <Section title="7. Intellectual Property">
                        <ul>
                            <li><strong>Goschedule.ai Property:</strong> All intellectual property rights in the Platform, including software, algorithms, AI models, workflows, branding, design, and proprietary methodologies, are and shall remain the exclusive property of Goschedule.ai.</li>
                            <li><strong>Client Data:</strong> The Client retains ownership of all data provided to Goschedule.ai for the purpose of service delivery. The Client grants Goschedule.ai a limited, non-exclusive license to use such data solely for the performance of the Services.</li>
                            <li><strong>Generated Content:</strong> Any outreach content, email templates, or lead intelligence reports generated through our Services are provided for the Client's business use. However, underlying systems and methodologies remain the property of Goschedule.ai.</li>
                            <li><strong>Restrictions:</strong> The Client may not copy, modify, distribute, or create derivative works of any Goschedule.ai proprietary technology or content without express written permission.</li>
                        </ul>
                    </Section>

                    <Section title="8. Confidentiality">
                        <p>
                            Both parties agree to maintain the confidentiality of any proprietary or sensitive information disclosed during the engagement. This obligation survives the termination of the agreement for a period of two (2) years. Confidential Information does not include information that is publicly available, independently developed, or lawfully obtained from a third party.
                        </p>
                    </Section>

                    <Section title="9. Termination">
                        <ul>
                            <li><strong>By the Client:</strong> The Client may terminate the engagement by providing thirty (30) days' written notice to Goschedule.ai. The Client shall remain liable for all fees due for Services rendered up to the effective date of termination.</li>
                            <li><strong>By Goschedule.ai:</strong> We reserve the right to suspend or terminate Services immediately if the Client breaches these Terms, engages in unlawful conduct, or fails to make timely payments.</li>
                            <li><strong>Effect of Termination:</strong> Upon termination, the Client's access to the Platform and all ongoing campaigns shall be discontinued. Data provided by the Client shall be returned or deleted within thirty (30) days, upon written request.</li>
                        </ul>
                    </Section>

                    <Section title="10. Disclaimer of Warranties">
                        <p>
                            The Services are provided on an "as is" and "as available" basis. Goschedule.ai disclaims all warranties, whether express, implied, or statutory, including but not limited to the warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Services will be uninterrupted, error-free, or free from harmful components.
                        </p>
                    </Section>

                    <Section title="11. Indemnification">
                        <p>
                            The Client agrees to indemnify, defend, and hold harmless Goschedule.ai, its officers, directors, employees, agents, and affiliates from and against any and all claims, damages, losses, liabilities, and expenses (including reasonable legal fees) arising from or relating to the Client's use of the Services, violation of these Terms, or infringement of any third-party rights.
                        </p>
                    </Section>

                    <Section title="12. Governing Law &amp; Jurisdiction">
                        <p>
                            These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising out of or relating to these Terms or the Services shall be subject to the exclusive jurisdiction of the courts located in India. The parties agree to attempt resolution through good-faith negotiation before pursuing formal legal proceedings.
                        </p>
                    </Section>

                    <Section title="13. Force Majeure">
                        <p>
                            Neither party shall be liable for any failure or delay in performance resulting from circumstances beyond its reasonable control, including but not limited to natural disasters, pandemics, war, government actions, power failures, internet disruptions, or third-party service outages.
                        </p>
                    </Section>

                    <Section title="14. Modifications to Terms">
                        <p>
                            Goschedule.ai reserves the right to update or modify these Terms at any time. Material changes will be communicated through our website or via email. Your continued use of the Services following the posting of changes constitutes acceptance of such changes.
                        </p>
                    </Section>

                    <Section title="15. Contact Information">
                        <p>If you have any questions, concerns, or requests regarding these Terms and Conditions, please contact us:</p>
                        <div style={{
                            background: 'var(--bg-raised)',
                            border: '1px solid var(--border-subtle)',
                            borderRadius: 'var(--card-radius)',
                            padding: 'var(--space-4)',
                            marginTop: 'var(--space-2)',
                        }}>
                            <p style={{ color: 'var(--text-primary)', fontWeight: 600, marginBottom: '8px' }}>Goschedule.ai</p>
                            <p>Email: <a href="mailto:hello@goschedule.ai" style={{ color: '#A5B4FC', textDecoration: 'underline' }}>hello@goschedule.ai</a></p>
                            <p>Website: <a href="https://goschedule.ai" style={{ color: '#A5B4FC', textDecoration: 'underline' }}>goschedule.ai</a></p>
                        </div>
                    </Section>

                </div>
            </div>
        </main>
    )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <section style={{
            background: 'var(--bg-raised)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--card-radius)',
            padding: 'var(--space-4)',
        }}>
            <h2 style={{
                fontSize: '20px',
                fontWeight: 600,
                color: 'var(--text-primary)',
                marginBottom: 'var(--space-2)',
                letterSpacing: '-0.01em',
            }}>{title}</h2>
            <div className="legal-content">
                {children}
            </div>
        </section>
    )
}
